package vi.viredis.commands;

public enum RedisProtocolCommand {

    AUTH, CLIENT, DBSIZE, DECR, DEL, EXEC, EXISTS, EXPIRE, GET, GETSET, GETNAME, INCR, LIST, LLEN, LPOP, LPUSH,
    LRANGE, LREM, MGET, MULTI, QUIT, RPOP, RPUSH, SADD, SCARD, SET, SISMEMBER,
    SETNAME, SORT, SREM, TIME, TTL, SMEMBERS, HGETALL ;
}
